apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: was-ingress-resources
  namespace: was
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /resources/$1
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
        - path: /?resources(?:$|/(.*))
          pathType: ImplementationSpecific
          backend:
            service:
              name: resource-manager
              port:
                number: 9090